

SELECT WAREHOUSE_ID,WAREHOUSE_NAME,ADDRESS, IFNULL(FREEZER_YN, 'N') AS FREEZER_YN
from FOOD_WAREHOUSE
where WAREHOUSE_NAME like '%경기%'
order by WAREHOUSE_ID asc;


/*
 1단계

SELECT WAREHOUSE_ID,WAREHOUSE_NAME,ADDRESS,FREEZER_YN
from FOOD_WAREHOUSE
order by WAREHOUSE_ID asc;


 2단계
 where 절에 like를 사용해 경기도에 위치한 창고를 추출
 SELECT WAREHOUSE_ID,WAREHOUSE_NAME,ADDRESS,FREEZER_YN
 from FOOD_WAREHOUSE
 where WAREHOUSE_NAME like '%경기%'
 order by WAREHOUSE_ID asc;


 3단계
IFNULL 사용 IFNULL(A, B) : A(컬럼)의 값이 NULL일 경우 B로 대체 ★

 SELECT WAREHOUSE_ID,WAREHOUSE_NAME,ADDRESS, IFNULL(FREEZER_YN, 'N') AS FREEZER_YN
from FOOD_WAREHOUSE
where WAREHOUSE_NAME like '%경기%'
order by WAREHOUSE_ID asc;


 다른방법:
 COALESCE 사용
 COALESCE(A, B) : A(데이터)가 NULL일 경우 B로 대체

SELECT WAREHOUSE_ID,WAREHOUSE_NAME,ADDRESS, COALESCE(FREEZER_YN, 'N') AS FREEZER_YN
from FOOD_WAREHOUSE
where WAREHOUSE_NAME like '%경기%'
order by WAREHOUSE_ID asc;





 */
