
select FH.FLAVOR
from FIRST_HALF FH JOIN ICECREAM_INFO II ON FH.FLAVOR = II.FLAVOR
where TOTAL_ORDER > 3000 and INGREDIENT_TYPE='fruit_based'
order by TOTAL_ORDER desc;

/**
  JOIN 절 사용 

 */




/*
 1단계
select FH.FLAVOR
from FIRST_HALF FH JOIN ICECREAM_INFO II ON FH.FLAVOR = II.FLAVOR




 2단계
select FH.FLAVOR
from FIRST_HALF FH JOIN ICECREAM_INFO II ON FH.FLAVOR = II.FLAVOR
where TOTAL_ORDER > 3000 and INGREDIENT_TYPE='fruit_based'





 3단계
select FH.FLAVOR
from FIRST_HALF FH JOIN ICECREAM_INFO II ON FH.FLAVOR = II.FLAVOR
where TOTAL_ORDER > 3000 and INGREDIENT_TYPE='fruit_based'
order by TOTAL_ORDER desc;






 */
SELECT FH.FLAVOR
FROM FIRST_HALF FH JOIN ICECREAM_INFO II ON FH.FLAVOR = II.FLAVOR
WHERE TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC
