SELECT ANIMAL_ID, NAME
from ANIMAL_INS
where  INTAKE_CONDITION != 'Aged'
order by ANIMAL_ID	asc;



/*
 1단계
 SELECT ANIMAL_ID, NAME
from ANIMAL_INS
where
order by ANIMAL_ID	asc;


2단계
SELECT ANIMAL_ID, NAME
from ANIMAL_INS
where  INTAKE_CONDITION != 'Aged'  //
order by ANIMAL_ID	asc;

 다른 풀이 != 대신 NOT IN , NOT
 SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION NOT IN ('Aged')
ORDER BY ANIMAL_ID ASC

 SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE NOT INTAKE_CONDITION = 'Aged'
ORDER BY ANIMAL_ID ASC



 */
