
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
from BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021 AND CATEGORY ="인문"
order by PUBLISHED_DATE asc;

// WHERE YEAR(PUBLISHED_DATE) = 2021 AND CATEGORY ="인문"


/*
 1단계
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
from BOOK;



 2단계
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
from BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021 AND CATEGORY ="인문"
order by PUBLISHED_DATE asc;





 3단계







 */
